apiVersion: v1
kind: Secret
metadata:
  name: zbi-password
  labels:
    {{- include "zbi.labels" . | nindent 4 }}
data:
  {{- $zbiSecretObj := (lookup "v1" "Secret" .Release.Namespace "zbi-password") | default dict }}
  {{- $zbiSecretData := (get $zbiSecretObj "data") | default dict }}
  {{- $zbiPassword := (get $zbiSecretData "password") | default (randAlphaNum 16 | b64enc) }}
  password: {{$zbiPassword}}
