app:
  version: v1
  versions:
    v1:
      version: v1
      templates:
        file: ./templates/app_templates_v1.tmpl
project:
  versions:
    v1:
      version: v1
      images:
        - name: authz
          version: v0.0.1
          url: jakinyele/authz-server:v0.0.1
          port: 50051
      templates:
        file: ./templates/project_templates_v1.tmpl
instances:
  - name: zcash
    type: zcash
    ports:
      service: 18232
      metrics: 9100
      envoy: 28232
    versions:
      v1:
        version: v1
        service:
          prefix: zcashd-svc
          proxyPort: 28232
        images:
          - name: node
            version: v4.3.0
            url: electriccoinco/zcashd:v5.3.0
            port: 18232
          - name: metrics
            version: v0.3.6
            url: electriccoinco/zcashd_exporter:v0.3.6
            port: 9100
        templates:
          file: ./templates/zcash_templates_v1.tmpl
        methods:
          addressindex: [getaddressbalance,getaddressdeltas,getaddressmempool, getaddresstxids, getaddressutxos]
          blockchain: [getbestblockhash,getblock,getblockchaininfo,getblockcount,getblockdeltas,getblockhash,getblockhashes,getblockheader,getchaintips,getdifficulty,getmempoolinfo,getrawmempool,getspentinfo,gettxout,gettxoutproof,gettxoutsetinfo,verifychain,verifytxoutproof,z_gettreestate]
          control: [getexperimentalfeatures,getinfo,getmemoryinfo,help,setlogfilter,stop]
          disclosure: [z_getpaymentdisclosure,z_validatepaymentdisclosure]
          generating: [generate,getgenerate,setgenerate]
          mining: [getblocksubsidy,getblocktemplate,getlocalsolps,getmininginfo,getnetworkhashps,getnetworksolps,prioritisetransaction,submitblock]
          network: [addnode,clearbanned,disconnectnode,getaddednodeinfo,getconnectioncount,getdeprecationinfo,getnettotals,getnetworkinfo,getpeerinfo,listbanned,ping,setban]
          rawtransactions: [createrawtransaction,decoderawtransaction,decodescript,fundrawtransaction,getrawtransaction,sendrawtransaction,signrawtransaction]
          util: [createmultisig,estimatefee,estimatepriority,validateaddress,verifymessage,z_validateaddress]
          wallet: [addmultisigaddress,backupwallet,dumpprivkey,dumpwallet,encryptwallet,getbalance,getnewaddress,getrawchangeaddress,getreceivedbyaddress,gettransaction,getunconfirmedbalance,getwalletinfo,importaddress,importprivkey,importpubkey,importwallet,keypoolrefill,listaddresses,listaddressgroupings,listlockunspent,listreceivedbyaddress,listsinceblock,listtransactions,listunspent,lockunspent,sendmany,sendtoaddress,settxfee,signmessage,z_exportkey,z_exportviewingkey,z_exportwallet,z_getbalance,z_getmigrationstatus,z_getnewaddress,z_getnotescount,z_getoperationresult,z_getoperationstatus,z_gettotalbalance,z_importkey,z_importviewingkey,z_importwallet,z_listaddresses,z_listoperationids,z_listreceivedbyaddress,z_listunspent,z_mergetoaddress,z_sendmany,z_setmigration,z_shieldcoinbase,z_viewtransaction,zcbenchmark,zcrawjoinsplit,zcrawkeygen,zcrawreceive,zcsamplejoinsplit]
  - name: Light Wallet Server
    type: lwd
    ports:
      service: 9067
      http: 9068
      envoy: 28232
    versions:
      v1:
        version: v1
        service:
          prefix: lwd-svc
          proxyPort: 28232
        images:
          - name: lwd
            version: v0.4.11
            url: electriccoinco/lightwalletd:v0.4.13
            port: 9067
        templates:
          file: ./templates/lwd_templates_v1.tmpl
