apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zbi.fullname" . }}-pvc
  labels:
    {{- include "zbi.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.persistenceVolume.storageClass}}
  resources:
    requests:
      storage: {{ .Values.persistenceVolume.size}}
